### ISSUE TITLE
$isIe() returns false on IE11

### ISSUE THREAD

**Issue by jvalente** [Doist/ICE#2]

**Comment by pmpinto** [comment]
It seems that `$getStyle(element, "height")` is a little bit unreliable in some browsers since it returns `auto` for some elements. To work around this I was considering using `element.offsetHeight` but in this case it would only be needed for IE.

Unfortunately, as @jvalente mentioned, `$isIe()` returns false on IE11. Is there a workaround for this?

**Comment by jvalente** [comment]
hey @pmpinto, feels a bit like a desert in here. :P did u manage to work this out?

**Comment by amix** [comment]
Hi @pmpinto and @jvalente 
- I am unsure if it's necessary to use $isIe any more, since IE 11+ is an excellent browser
- `element.offsetHeight` is probably more correct than using `$getStyle(element, "height")`

**Comment by pmpinto** [comment]
Hey @jvalente! I only needed `$isIe()` to make sure I was getting the proper height value, so I ended up using `element.offsetHeight` since it worked pretty much everywhere.

https://github.com/Doist/Todoist_Static/blob/05dd2b9a16b259659be899965e98aefa19769ec2/landing_pages/static/apps/landing_pages/js/Sticky.js#L59-L62

**Comment by amix** [comment]
@pmpinto I would generally recommend using ES6 and using pure JavaScript in a ton of places -- since vanilla JS is becoming quite nice to work with. Check out http://youmightnotneedjquery.com/ 😊

**Comment by pmpinto** [comment]
Thanks @amix! I think Jano shared this website with me earlier. It's a good resource to have at hand, for sure.
